### ISSUE TITLE
تعداد شیٔ ها کم است

### ISSUE THREAD

**Issue by ghost** [armanyazdi/esm-famil-api#1]
من هنوز این اِی پی آی را امتحان نکردم ولی بنظرم جالب میاد، به نظر من می تواند با اضافه کردن آشیأ بیشتر این اِی پی آی را بهتر کنید

**Comment by armanyazdi** [comment]
hatman ezafe mishe. shoma ham age dataei baraye ashiya darid mitunid fork konid ezafe konid man merge mikonam.

**Comment by ghost** [comment]
85(84 -> 169) کلمه ی جدید اضافه شد. بعدا هم کلمات جدید اضافه خواهد شد https://github.com/manifarizi/esm-famil-api

**Comment by armanyazdi** [comment]
pull request bedid merge konam.

**Comment by ghost** [comment]
closed
