### ISSUE TITLE
last names file is wrong!

### ISSUE THREAD

**Issue by mrakhgari** [armanyazdi/esm-famil-api#4]
The `lastnames.txt` has the content of the `names.txt` file.

**Comment by armanyazdi** [comment]
Check [NameGenerator.java](https://github.com/armanyazdi/esm-famil-api/blob/master/src/main/java/com/armanyazdi/esmfamilapi/NameGenerator.java) class, it generates last names using the first names.

Also you can use this feature as a Python package:
https://github.com/armanyazdi/persian-names
